config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  root to: "home#index"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  namespace :admin do
    get "dashboard", to: "dashboard#index"
    root to: "dashboard#index"
    resources :categories
    resources :items
  end

  direct :cdn_image do |model, options|
    expires_in = options.delete(:expires_in) { ActiveStorage.urls_expire_in }
    cdn_host = Rails.env.production? ? Rails.application.credentials.cdn_host : "localhost"

    if model.respond_to?(:signed_id)
      route_for(
        :rails_service_blob_proxy,
        model.signed_id(expires_in: expires_in),
        model.filename,
        options.merge(host: cdn_host)
      )
    else
      signed_blob_id = model.blob.signed_id(expires_in: expires_in)
      variation_key  = model.variation.key
      filename       = model.blob.filename

      route_for(
        :rails_blob_representation_proxy,
        signed_blob_id,
        variation_key,
        filename,
        options.merge(host: cdn_host)
      )
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  validates :name, presence: true

  has_one_attached :image do |img|
    img.variant(:micro, resize_to_limit: [ 160, 160 ])
    img.variant(:mini, resize_to_limit: [ 350, 350 ])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  layout "admin/layout"
  before_action :set_item, only: [ :edit, :update, :destroy ]
  before_action :set_categories, only: [ :new, :create, :edit ]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to admin_items_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to admin_items_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy
    redirect_to admin_items_url
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def set_categories
    @categories = Category.all
  end

  def item_params
    params.expect(item: [ :name, :desc, :category_id, :image ])
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
  def image_link_tag_generator(item)
    item.image.attached? ? link_to(image_tag(item.image.variant(:micro)), item.image) : "No 🖼️"
  end

  def cdn_image_link_tag_generator(item)
    item.image.attached? ? link_to(image_tag(cdn_image_url(item.image.variant(:micro))), cdn_image_url(item.image)) : "No 🖼️"
  end

  def url_variants_link(item)
    if item.image.attached?
      variants = [ :mini, :micro ].map { |variant| link_to(variant, item.image.variant(variant)) }
      safe_join(variants, " ")
    else
      "No 🖼️"
    end
  end

  def cdn_url_variants_link(item)
    if item.image.attached?
      variants = [ :mini, :micro ].map { |variant| link_to(variant, cdn_image_url(item.image.variant(variant))) }
      safe_join(variants, " ")
    else
      "No 🖼️"
    end
  end
end

app/views/admin/items/_form.html.erb
<%= form_with model: [:admin, @item] do |f| %>
  <!-- Campo Nombre -->
  <div class="mb-4">
    <%= f.label :name, class: "mb-2 block text-sm font-bold text-gray-700" %>
    <%= f.text_field :name, placeholder: "Enter the name of item", class: "w-full rounded-md border border-gray-300 px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:outline-none", required: true %>
  </div>
  <!-- Campo Categorias -->
  <div class="mb-4">
    <%= f.label :category_id, class: "mb-2 block text-sm font-bold text-gray-700" %>
    <%= f.collection_select :category_id, @categories, :id, :name, { prompt: "Seleccione una categoría" }, { class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500", required: true } %>
  </div>
  <!-- Campo Descripción -->
  <div class="mb-6">
    <%= f.label :desc, "Description", class: "mb-2 block text-sm font-bold text-gray-700" %>
    <%= f.textarea :desc, rows: 4, placeholder: "Enter the description of item", class: "w-full rounded-md border border-gray-300 px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:outline-none", required: true %>
  </div>
  <!-- Campo para la imagen -->
  <div class="mb-6">
    <%= f.label :image, "Image", class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= f.file_field :image, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500", accept: "image/*" %>
    <% if @item.image.attached? %>
      <div class="mt-4">
        <p class="text-sm text-gray-600">Imagen actual:</p>
        <%= image_tag @item.image.variant(:micro), class: "mt-2 w-32 h-32 object-cover rounded-md" %>
      </div>
    <% end %>
  </div>
  <!-- Botón de Enviar -->
  <div class="flex justify-between">
    <%= link_to "cancel", admin_items_url, class: "bg-red-500 text-white p-2 rounded-lg hover:bg-red-600" %>
    <%= f.submit class: "bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-green-500 cursor-pointer" %>
  </div>
<% end %>

app/views/admin/items/_header.html.erb
<header class="bg-white shadow p-4 mb-8 rounded-lg">
  <div class="flex justify-between items-center">
    <h2 class="text-xl font-semibold">Items List</h2>
    <div class="flex items-center">
      <%= link_to "New Item", new_admin_item_path, class: "bg-blue-500 text-white p-2 rounded-lg hover:bg-blue-600" %>
    </div>
  </div>
</header>

app/views/admin/items/_item.html.erb
<div class="item flex border-b border-gray-200 hover:bg-gray-100">
  <div class="name w-1/3 py-3 px-4"><%= item.name %></div>
  <div class="desc w-1/3 py-3 px-4"><%= item.desc %></div>
  <div class="desc w-1/3 py-3 px-4"><%= item.category.name %></div>
  <div class="desc w-1/3 py-3 px-4"><%= image_link_tag_generator(item) %></div>
  <div class="desc w-1/3 py-3 px-4"><%= cdn_image_link_tag_generator(item) %></div>
  <div class="desc w-1/3 py-3 px-4"><%= url_variants_link(item) %></div>
  <div class="desc w-1/3 py-3 px-4"><%= cdn_url_variants_link(item) %></div>
  <div class="actions w-1/3 py-3 px-4 text-right inline">
    <%= link_to "📝", edit_admin_item_path(item), title: "Editar",
      class: "no-underline pr-1" %>
    <%= button_to admin_item_path(item), method: :delete, form: {data: {turbo_confirm: "Are your sure?"}},
      title: "Eliminar", class: "pr-1" do %>
      🚮
    <% end %>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="edit_item">
  <div class="container mx-auto">
    <div class="mx-auto max-w-md rounded-lg bg-white p-6 shadow-md">
      <h2 class="mb-6 text-2xl font-semibold text-gray-800">Edit Item Form</h2>
      <!-- Formulario -->
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<%= render "header" %>
<div class="items">
  <div class="container mx-auto">
    <div class="bg-white shadow-md rounded-lg overflow-hidden">
      <!-- table header -->
      <div class="flex bg-gray-200 text-gray-700 uppercase text-sm leading-normal">
        <div class="w-1/3 py-3 px-4 font-semibold">Name</div>
        <div class="w-1/3 py-3 px-4 font-semibold">Description</div>
        <div class="w-1/3 py-3 px-4 font-semibold">Category</div>
        <div class="w-1/3 py-3 px-4 font-semibold">Image</div>
        <div class="w-1/3 py-3 px-4 font-semibold">CDN Image</div>
        <div class="w-1/3 py-3 px-4 font-semibold">URL Variants</div>
        <div class="w-1/3 py-3 px-4 font-semibold">CDN URL Variants</div>
        <div class="w-1/3 py-3 px-4 font-semibold text-right">Actions</div>
      </div>
      <!-- table rows -->
      <div class="flex flex-col">
        <% if @items.any? %>
          <!-- rows -->
          <%= render @items %>
        <% else %>
          <p>No items yet</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="new_item">
  <div class="container mx-auto">
    <div class="mx-auto max-w-md rounded-lg bg-white p-6 shadow-md">
      <h2 class="mb-6 text-2xl font-semibold text-gray-800">New Item Form</h2>
      <!-- Formulario -->
      <%= render "form" %>
    </div>
  </div>
</div>