config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  root to: "home#index"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  namespace :admin do
    get "dashboard", to: "dashboard#index"
    root to: "dashboard#index"
    resources :categories
    resources :items
  end

  direct :cdn_image do |model, options|
    expires_in = options.delete(:expires_in) { ActiveStorage.urls_expire_in }
    cdn_host = Rails.env.production? ? Rails.application.credentials.cdn_host : "localhost"

    if model.respond_to?(:signed_id)
      route_for(
        :rails_service_blob_proxy,
        model.signed_id(expires_in: expires_in),
        model.filename,
        options.merge(host: cdn_host)
      )
    else
      signed_blob_id = model.blob.signed_id(expires_in: expires_in)
      variation_key  = model.variation.key
      filename       = model.blob.filename

      route_for(
        :rails_blob_representation_proxy,
        signed_blob_id,
        variation_key,
        filename,
        options.merge(host: cdn_host)
      )
    end
  end
end

app/views/layouts/admin/_flash.html.erb
<div class="flashes">
  <% flash.each do |type, message| %>
    <%= content_tag(:div, message,
                    class: "flash #{type}",
                    data: {controller: "flash"}
                   ) %>
  <% end %>
</div>

app/views/layouts/admin/_header.html.erb
<header class="bg-gray-100">
  <nav class="mx-auto flex max-w-7xl items-center p-6 lg:px-8">
    <div class="absolute left-1/2 transform -translate-x-1/2">
      <%= link_to admin_dashboard_path do %>
        <h1 class="text-2xl font-bold text-gray-900">Image Storage</h1>
      <% end %>
    </div>
    <div class="ml-auto">
      <p class="text-sm text-gray-900 mr-4 truncate">Hello <%= Current.user.email_address %></p>
      <%= link_to "Log Out", session_path, method: :delete, class: "text-sm/6 font-semibold text-gray-900 hover:text-gray-700", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to log out?" } if authenticated? %>
    </div>
  </nav>
</header>

app/views/layouts/admin/_sidebar.html.erb
<aside class="w-64 bg-blue-800 text-white p-6">
  <h1 class="text-2xl font-bold mb-8">Admin Panel</h1>
  <nav>
    <ul>
      <li class="mb-4">
        <%= link_to admin_dashboard_url, class: "flex items-center hover:bg-blue-700 p-2 rounded" do %>
          <span class="mr-2">📊</span>
          Dashboard
        <% end %>
      </li>
      <li class="mb-4">
        <%= link_to admin_categories_url, class: "flex items-center hover:bg-blue-700 p-2 rounded" do %>
          <span class="mr-2">🗂️</span>
          Categories
        <% end %>
      </li>
      <li class="mb-4">
        <%= link_to admin_items_url, class: "flex items-center hover:bg-blue-700 p-2 rounded" do %>
          <span class="mr-2">⚙️</span>
          Items
        <% end %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/admin/layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Image Storage" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-gray-100">
    <%= render "layouts/admin/header" %>
    <div class="flex h-screen">
      <div id="flash">
        <%= render "layouts/admin/flash" %>
      </div>
      <!-- sidebar -->
      <%= render "layouts/admin/sidebar" %>
      <!-- main content -->
      <main class="flex-1 p-8">
        <%= yield %>
      </main>
    </div>
  </body>
</html>